third commit

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -22,6 +22,23 @@ jobs:
     - uses: actions/upload-artifact@v4
       if: always()
       with:
-        name: playwright-report
-        path: playwright-report/
-        retention-days: 30
+    - name: Check for report folder
+      run: |
+        if [ -d "playwright-report" ]; then
+          echo "Report exists";
+        else
+          echo "Report folder not found" && exit 1;
+        fi
+
+    - name: Upload Playwright report
+      if: success() || failure()
+      uses: actions/upload-artifact@v4
+      with:
+      name: playwright-report
+      path: playwright-report/
+      retention-days: 30
+        
+
+
+
+        
